version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/aws-codepipeline-0.0.1-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes